### PR TITLE
Permission changer

### PR DESCRIPTION
**Pull request by SKART1**
#18 implemented based on code sample from [tweet](https://twitter.com/ppvi/status/760838946788143106) and from code [example](https://github.com/googlesamples/android-testing/blob/ed62c450e43f859333b3113d44dd59f75971b529/ui/espresso/IntentsBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DialerActivityTest.java#L94)

### CODE REVIEW

**Comment by drewhannay** [comment]
This is easily solved by just installing the app with the -g flag to grant all permissions. No need for Test Butler to do this.

**Comment by SKART1** [comment]
Yes -g flag works. 
But there are scenarios in which you actually testing permission system. For example: 
```
public class TestAccessToCamera {
     @Test
     public void TestIfPermissionAlreadyGranted(){
     }

     @Test
     public void TestIfPermissionGranted(){
     }

     @Test
     public void TestIfPermissionNotGranted(){
     }
}
```

Instead of completely reinstall app you may just revoke permissions in `@Before` methods

**Comment by drewhannay** [comment]
These situations are usually better tested with unit tests. If you really wanted to verify the end to end behavior of your app, you'd need to use UiAutomator and actually grant the permissions the way a user normally would.

Also, I believe granting a permission to an app causes the app process to restart, which would break Instrumentation tests anyway.

**Comment by SKART1** [comment]
> These situations are usually better tested with unit tests. If you really wanted to verify the end to end behavior of your app, you'd need to use UiAutomator and actually grant the permissions the way a user normally would.

UIAutomator can not **revoke** permissions. 
I have described case in which each of the tests methods should have own state of permissions at the beginning of the test

> Also, I believe granting a permission to an app causes the app process to restart, which would break Instrumentation tests anyway.

See the tests. No restarts happened during granting/revoking permission

**Pull request closed without merging**
